AppBundle\Entity\Conyugue:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\ConyugueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numeroIdentificacion:
            type: string
            length: '10'
        tipoIdentificacion:
            type: string
            length: '2'
        nombreUsuario:
            type: string
            length: '25'
        primerNombre:
            type: string
            length: '100'
        segundoNombre:
            type: string
            length: '100'
        primerApellido:
            type: string
            length: '100'
        segundoApellido:
            type: string
            length: '100'
        fechaNacimiento:
            type: date
            length: null
        genero:
            type: string
            length: '1'
        telefono:
            type: string
            length: '10'
        empresa:
            type: string
            length: '100'
        ocupacion:
            type: string
            length: '100'
    lifecycleCallbacks: {  }
