<?php

namespace AppBundle\Entity;

/**
 * ConyugueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConyugueRepository extends \Doctrine\ORM\EntityRepository
{
}
