<?php

namespace AppBundle\Entity;

/**
 * HijoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HijoRepository extends \Doctrine\ORM\EntityRepository
{
}
